### ISSUE TITLE
Should we consider adjusting the travis test to allow longer python code?

### ISSUE THREAD

**Issue by hackthehackerman** [Connexions/cnx-archive#436]
My commit Connexions/cnx-archive@1ae929e is failing the Travis CI test because it contains line longer than 79 chars after autopep8 formatting. Although I think the line limit is necessary to make codes readable, it shouldn't be strictly required since there are instances (like this) that longer codes brings benefits. In this case, longer code allows saner variable naming.

**Comment by hackthehackerman** [comment]
@edwoodward what do you think of this?

**Comment by edwoodward** [comment]
I think line length requirements are unnecessary. It is a pep8 standard. Can you use one of the suggested ways to deal with long lines? - https://www.python.org/dev/peps/pep-0008/#maximum-line-length. @reedstrm @pumazi @karenc Suggestions?

**Comment by pumazi** [comment]
pep8 is our coding style. It keeps us consistent and prevents sloppy mistakes. I've been caught by it several times, but I go back and fix my error. I personally find the tool to be very useful.

We have been more relaxed with pep8 in terms of the tests, because some of the SQL queries can become lengthy and we don't put them into separate files like we do for the main SQL. This shouldn't be and isn't the case for our main logic.

In this instance, one of the existing lines was change (see line 47 of database.py) and triggered our pep8 tool to raise an error. With that said, the solution to this issue is currently in the file. That is, drop the function parameter to the next line and indent it.

(Not to get off topic, but there as also some stray files in commit mentioned.)

**Comment by hackthehackerman** [comment]
Thanks @pumazi , I will go back and fix them.
