### ISSUE TITLE
Simulations have a jquery security issue: Fix & Test 1 Sim

### ISSUE THREAD

**Issue by brittweinstein** [Connexions/cnx-archive#583]
# Scenario

Github sent out a security alert about a jquery security issue in the Simulations repo. The version of jquery should be updated.

>Warning! 	
>Connexions / simulations
>
>Known security vulnerabilities detected
>Dependency jquery 	Version > 2.1.0 < 3.0.0 	Upgrade to ~> 3.0.0
Vulnerabilities
>CVE-2016-10707 Moderate severity
>CVE-2015-9251 Moderate severity
>CVE-2015-9251 Moderate severity
>CVE-2016-10707 Moderate severity
>	Defined in package.json 	

# The Plan
(Approved by CNX devs, Kerwin, Ed, Carly, Alina)
We will fix the code & test 1 sim for the 9/24 release in order to see how much work this will be later.  Tom to lead and bring in Nathan as-needed.  
Then, we will size the work for the rest of the sims and possibly contract the rest of the work out.

# PRs
https://github.com/Connexions/simulations/pull/448

**Comment by openstaxalina** [comment]
Decision: we will update the version of jQuery; however, we need to review the impact to simulations and the testing load.  This will allow us to determine when to release this change.

**Comment by kerwinso** [comment]
All simulations will need to be regression tested. Patrick (the original animator) wrote documentation on how the simulations should behave, Kathi should know where this documentation is.

**Comment by reedstrm** [comment]
Tom found this:

https://jquery.com/upgrade-guide/3.0/

Looks pretty extensive.

**Comment by brittweinstein** [comment]
Decision: we will try to do 1 for this release in order to see how much work this will be later.

**Comment by brittweinstein** [comment]
@openstaxalina will update Ed with this plan.

**Comment by openstaxalina** [comment]
Ed & Carly are on board with doing this for 1 sim for the 9/24 release.

**Comment by TomWoodward** [comment]
i updated that battery resistor exercise jquery, bootstrap, and ran `npm audit fix --force` for that sim

the only npm update that seemed to break anything was less, so i rolled that back to where it was and now npm only reports `found 10 vulnerabilities (1 low, 9 moderate)` instead of found `81 vulnerabilities (21 low, 36 moderate, 22 high, 2 critical)`

production is here:
https://archive.cnx.org/specials/ee4d9924-b4ce-11e5-84cb-4b93623233d2/battery-resistor-circuit/

the version i updated is here:
http://connexions.github.io/simulations/battery-resistor-circuit/#sim-battery-resistor-circuit

to verify new version of jquery run `jQuery().jquery` in the console, old version was `2.1.4`, new version is `3.3.1`

**Comment by kerwinso** [comment]
Functional testing will happen on github pages.
We will need a hand deploy to staging for regression testing. We also need to update jquery on staging and verify the new jquery version on staging.

**Comment by kerwinso** [comment]
The simulations linked to in [Tom's comment above](https://github.com/Connexions/cnx-archive/issues/583#issuecomment-419489417) (prod vs. gh pages) are functionally and visually identical, so testing passed. Need to check again once deployed to https://archive-staging.cnx.org/specials.

**Comment by kerwinso** [comment]
https://archive-staging.cnx.org/specials/ee4d9924-b4ce-11e5-84cb-4b93623233d2/battery-resistor-circuit/#sim-battery-resistor-circuit: Passed functional testing. 
`jQuery().jquery` returns `3.3.1`.
